### ISSUE TITLE
Trouble installing python-mander

### ISSUE THREAD

**Issue by michaelaoash** [gerrymandr/python-mander#21]
I have successfully installed and run mandeR in R and have compactnesslib, etc., installed. 
I am trying to run python-mander.  I am new to python.  I am running python3 (on ubuntu linux 21.04).   I have the virtualenv working.

When I run  `pip install -r requirements.txt` I get errors for functools32 and wsgiref.  Are these essential?  If I delete these lines, the other requirements install.  At this point, i.e., without functools32 and wsgiref but with everything else,  `python setup.py build` runs without errors. 

When I launch python and try `import mander`  I get the following:
```
>>> import mander
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/Desktop/python-mander/mander/__init__.py", line 1, in <module>
    import _mander
ModuleNotFoundError: No module named '_mander'
```
Please let me know if you have any suggestions for installation. Thanks.

**Comment by liamrahav** [comment]
I have the same issue as above.
